baseurl = "/"
languageCode = "en-us"
title = "Apuntes"
theme = "cactus"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Sobre mi"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/snaraya/"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/turumpsss"

[params]
    description = "Currently reading: Alguien camina sobre tu tumba de Mariana Enr√≠quez."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[markup.goldmark.renderer]
    unsafe = true